### PR TITLE
feat: install examples for top level builds

### PR DESCRIPTION
**Pull request by Scrumplex**
**What does this change do?**

This change installs built examples as binaries. 
This might be useful for distribution packagers to provide these example programs in their packages.

**Is it related to an existing bug report or feature request?**

N/A

**Pre-merge checklist**

-   [x] I've read [CONTRIBUTING.md]
-   [x] I've rebased my changes against the current HEAD of `origin/master` (if necessary)
-   [ ] I've added new test cases to verify my change
-   [ ] I've regenerated toml.hpp ([how-to])
-   [ ] I've updated any affected documentation
-   [x] I've rebuilt and run the tests with at least one of:
    -   [ ] Clang 8 or higher
    -   [x] GCC 8 or higher
    -   [ ] MSVC 19.20 (Visual Studio 2019) or higher
-   [x] I've added my name to the list of contributors in [README.md](https://github.com/marzer/tomlplusplus/blob/master/README.md)

[CONTRIBUTING.md]: https://github.com/marzer/tomlplusplus/blob/master/CONTRIBUTING.md
[how-to]: https://github.com/marzer/tomlplusplus/blob/master/CONTRIBUTING.md#regenerating-tomlhpp
[README.md]: https://github.com/marzer/tomlplusplus/blob/master/README.md

### CODE REVIEW

**Comment by marzer** [comment]
Hmmmn, I think this should also have an option to control it, and be off by default. I know I personally have never wanted the INSTALL target of a project to install examples/demos/tests, et cetera, when I was doing a system build; I imagine many others are the same.

**Comment by Scrumplex** [comment]
I would argue that setting `-Dbuild_examples=true` would only make sense in the context of a system build if those examples are also installed. Otherwise, it doesn't really make much sense to build those examples when your intent is to package the software for a system build.

**Comment by marzer** [comment]
I don't want example binaries to install by default. This is standard pratice.

**Comment by marzer** [comment]
Oh, wait a minute, I get what you're saying now. People have to opt-in to building the examples to begin with, heh. Sorry, brain-fart. Yeah this makes sense.

**Review by marzer — APPROVED** [review]

**Comment by Scrumplex** [comment]
Oh, I didn't see your comment before pushing. Lemme reset back ^^

**Comment by marzer** [comment]
🎉 cheers :)

**Pull request merged**
