### PR TITLE
Add the Cmake configuration files support (#22) [skip ci]

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
The PR introduces the support for the CMake config file. In detail, the `meson build` system is used to generate a basic Cmake configuration file. Please find more information [here](https://mesonbuild.com/CMake-module.html#cmake-configuration-files).

This PR fixes https://github.com/marzer/tomlplusplus/issues/20

### CODE REVIEW

**Comment by traversaro** [comment]
Something that I realized by looking at the pkg-config file added  in https://github.com/marzer/tomlplusplus/pull/16, is that probably it would be better to agree on a consistent package name between pkg-config and CMake config files. In my comments I was using `tomlplusplus` for the package name and `tomplusplus::tomlplusplus` for the imported target name, but in  https://github.com/marzer/tomlplusplus/pull/16 they used `toml++` as a package name, so perhaps it is better to stick to that. I used `tomplusplus` because I am always a bit afraid of using characters outside of  POSIX-defined  "Portable Filename Character Set" https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap03.html#tag_03_276, but probably using a `+` in a filename is probably ok in most modern, and we can use `toml++` for the CMake package name and `toml++::toml++` for the imported target, @marzer do you have any opinion on this?

**Comment by marzer** [comment]
@traversaro I think being consistent is good, though I don't much care whether it's `toml++` or `tomlplusplus`.

**Comment by traversaro** [comment]
Ok, in that case I would then change (fyi @GiulioRomualdi ) https://github.com/marzer/tomlplusplus/blob/master/meson.build#L108 to `name: meson.project_name(),` .

**Comment by marzer** [comment]
Ah, right, that's a good idea.

Now that I think about it I think meson might have even prevented me from using `toml++` as the project name when I first set it up...

**Comment by marzer** [comment]
Changed to `meson.project_name()` in dce20a7.

**Comment by traversaro** [comment]
Great, then I think this PR is good to go.

**Comment by marzer** [comment]
🎉 

Thanks for your feedback and contributions gentlemen!

**Pull request merged**
