### PR TITLE
Added CMake FetchContent information

### PR DESCRIPTION
**Pull request by proydakov**
Hi, marzer.

I added new integration instruction for CMake FetchContent in Readme.
Could you review & accept my changes, pls?

Best regards, Proydakov Evgeny.

### CODE REVIEW

**Comment by marzer** [comment]
Thanks for this! Could you also add a section to `docs/pages/main_page.dox` so the information will appear on [marzer.github.io/tomlplusplus](https://marzer.github.io/tomlplusplus/)?

**Comment by proydakov** [comment]
Let me check `docs/pages/main_page.dox`

**Comment by proydakov** [comment]
@marzer I updated docs/pages/main_page.dox. Could you review my changes, pls?

**Comment by marzer** [comment]
Looks good. Thanks for the contribution!

**Pull request merged**
