### PR TITLE
docs: fix some Markdown issues

### PR DESCRIPTION
**Pull request by Tachi107**
This small patch fixes some minor Markdown issues in the README and CONTRIBUTING files:

- Add a blank line before and after block elements like lists and code blocks. This specified in the [original Markdown syntax] document, and can also create some issues with some parsers (see [MD32]).
- Add a blank line around headings, for the same reasons as above.
- Only use one top-level (H1) heading per document.
- Always specify a language in fenced code blocks, so that plugins like highlight.js can correctly highlight them
- Remove unused links from the bottom of README.md.

[original Markdown syntax]: https://daringfireball.net/projects/markdown/syntax
[MD32]: https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md032

I also wanted to fix CHANGELOG.md, but it looks auto-generated so I did not touch it.

### CODE REVIEW

**Comment by marzer** [comment]
> I also wanted to fix CHANGELOG.md, but it looks auto-generated

Nope, that's all me - have at it :)

**Comment by Tachi107** [comment]
Done. I tried to fix most [markdownlint] violations, but I can see how you may not like some of the more opinionated changes. Let me know if I have to change something :)

[markdownlint]: https://github.com/DavidAnson/markdownlint

**Comment by marzer** [comment]
Opinionated? It seems to be mostly just blank lines - I'm not too fussy about that.  I didn't realise there were markdown parsers that benefitted from that, tbh.

Looks good to me :)

**Comment by Tachi107** [comment]
Il giorno sab 24 set 2022 alle 08:21:11 -07:00:00, Mark Gillard 
***@***.***> ha scritto:
> Opinionated? It seems to be mostly just blank lines - I'm not too 
> fussy about that. I didn't realise there were markdown parsers that 
> benefitted from that, tbh.

Maybe opinionated isn't the best word; I meant kinda useless. Putting 
blank lines before and after lists and code blocks is mandated by the 
spec (and required by some less flexible parsers), but e.g. avoiding 
multiple blank lines doesn't really change anything, as multiple blank 
lines are simply ignored.

Anyway, thanks for merging :)

**Comment by Tachi107** [comment]
Done. I tried to fix most [markdownlint] violations, but I can see how 
you may not like some of the more opinionated changes. Let me know if I 
have to change something :)

[markdownlint]: https://github.com/DavidAnson/markdownlint

**Pull request merged**
