### PR TITLE
build(meson): general improvements and fixes

### PR DESCRIPTION
**Pull request by Tachi107**
**What does this change do?**

Use the `/` operator instead of join_paths

Use the `/` operator instead of using "/" in string paths

Use the `includedir` opt instead of hardcoding "include" in `install_subdir`

Remove discouraged `layout=flat` option (mesonbuild/meson#9243)

Remove unneeded -Wextra, -Wpedantic flags, already added by `warning_level=3`

Remove manual -Oz flag when using Clang (mesonbuild/meson#9286)

Make use of : in kwargs consistent

**Pre-merge checklist**

- [x] I've read [CONTRIBUTING.md]
- [x] I've rebased my changes against the current HEAD of `origin/master` (if necessary)
- [ ] I've added new test cases to verify my change
- [ ] I've regenerated toml.hpp ([how-to])
- [ ] I've updated any affected documentation
- [ ] I've rebuilt and run the tests with at least one of:
    - [ ] Clang 6 or higher
    - [ ] GCC 7 or higher
    - [ ] MSVC 19.20 (Visual Studio 2019) or higher
- [x] I've added my name to the list of contributors in [README.md](https://github.com/marzer/tomlplusplus/blob/master/README.md)

[CONTRIBUTING.md]: https://github.com/marzer/tomlplusplus/blob/master/CONTRIBUTING.md
[how-to]: https://github.com/marzer/tomlplusplus/blob/master/CONTRIBUTING.md#regenerating-tomlhpp
[README.md]: https://github.com/marzer/tomlplusplus/blob/master/README.md

### CODE REVIEW

**Comment by Tachi107** [comment]
Didn't have time to run the tests, so I'm marking this as draft

**Comment by Tachi107** [comment]
I won't be able to run the tests until this afternoon, but since all tests passed in CI I think that it is safe to mark this as ready for review

**Comment by marzer** [comment]
Oh nice, I've learned a few things about meson from this PR. LGTM!

**Comment by marzer** [comment]
Oh nice, I've learned a few things about meson from this PR. LGTM!

**Pull request merged**
